version: "3.8"

services:
  server:
    network_mode: host
    env_file:
      - .env
    build:
      context: ./
      dockerfile: .dockerfiles/backend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      OLLAMA_URL: "${OLLAMA_URL}"
      DB_URL: "${DB_URL}"
  ollama:
    network_mode: host
    env_file:
      - .env
    build:
      context: ./
      dockerfile: .dockerfiles/ollama.dockerfile
    ports:
      - "11434:11434"
  db:
    network_mode: host
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD}"
volumes:
  server:
  db:
  shared-config: